spring.application.name=Test

spring.datasource.url=jdbc:sqlserver://Nestor_C:1433;databaseName=Tienda;encrypt=false;trustServerCertificate=true
spring.datasource.username=springapp
spring.datasource.password=SpringApp2026*
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

jwt.secret=12345678901234567890123456789012
jwt.expiration=86400000
